# Automatic changelog and version bumping with release-please for python projects
name: Release-please 🐍

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Create release PR
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
            # TODO: Use a personal access token so releases created by this workflow can trigger the deployment workflow
            token: ${{ secrets.GITHUB_TOKEN }}
            config-file: release-please-config.json
